### ISSUE TITLE
logging erros

### ISSUE THREAD

**Issue by abhisharma404** [abhisharma404/vault_scanner#1]
Instead of printing errors we can safely log them into a file.

**Comment by 0xPrateek** [comment]
Is this issue done ?

**Comment by abhisharma404** [comment]
@mzfr Are you working on this?

**Comment by mzfr** [comment]
@abhisharma404 yes I'll be submitting the PR soon

**Comment by 0xPrateek** [comment]
I am also working on this issue but I am thinking to use file handling for it . Instead of using logging module

**Comment by 0xPrateek** [comment]
What you say should I work on it.?
