### ISSUE TITLE
Implement a web crawler using Scrapy

### ISSUE THREAD

**Issue by abhisharma404** [abhisharma404/vault_scanner#13]
Implement a web crawler using Scrapy.

You can read about Scrapy here : https://scrapy.org/
Create a separate module for this, put it inside the `src/lib/crawler` folder and connect `vault.py` to it.

**Comment by SohailAlvi** [comment]
I am interested in working on this issue.

**Comment by abhisharma404** [comment]
Go ahead :) Expecting your PR soon.
