### ISSUE TITLE
URL parsing in vault.py

### ISSUE THREAD

**Issue by abhisharma404** [abhisharma404/vault_scanner#14]
Currently user can pass URL as -u 'www.url...' in `vault.py`.
We do not modify or try to check the URL and the URL is straightly forwarded to other modules.

List of URLs passed by user that seem right but they result in error : 
1. `example.com`
2. `www.example.com`

The correct form is:
`http://www.example.com`

We can implement an intelligence system that modifies the URL passed by the user accordingly.
This intelligence system is meant to be in the `vault.py` file itself.

**Comment by mzfr** [comment]
@abhisharma404 We use regex to parse the entered URL and then see if the scheme is missing or not.

**Comment by abhisharma404** [comment]
Yes that's great, can you work on this and send a PR?

**Comment by mzfr** [comment]
sure will do that :smile:
