### ISSUE TITLE
colored printing

### ISSUE THREAD

**Issue by abhisharma404** [abhisharma404/vault_scanner#4]
Instead of printing white text we can use beautiful combination of red and green to print error and success messages and so on.
Colorama would work great! :)

**Comment by mzfr** [comment]
Why colorama? I mean we do have ascii colors predefined in [colors.py](https://github.com/abhisharma404/vault_scanner/blob/master/src/colors.py), we can use that also, right?

**Comment by mzfr** [comment]
@abhisharma404 any thoughts on this?

**Comment by abhisharma404** [comment]
@mzfr Sure, ASCII colors would work great. 
I guess that was before `colors.py` was added!
