### ISSUE TITLE
adding JSON or text file output

### ISSUE THREAD

**Issue by abhisharma404** [abhisharma404/vault_scanner#8]
We can extend all the features of Vault to generate a beautiful custom output, which can be in JSON or a simple text file.

**Comment by rjt-gupta** [comment]
I can work on this.

**Comment by abhisharma404** [comment]
@rjt-gupta Go ahead :)

**Comment by AviBomb** [comment]
@abhisharma404 if this hasn't been done yet i would like to work on this

**Comment by abhisharma404** [comment]
@AviBomb I guess rjt-gupta is working on this, and most of the parts have been implemented!

**Comment by rjt-gupta** [comment]
Yeah im almost done with this. Soon will send the final PRs

**Comment by AviBomb** [comment]
Ok Sure will work on something else
